"""opsaudit audits disparity signals in operational decision systems."""

__version__ = "0.2.0"

from .agents import (
    GENERATORS,
    AuditCampaign,
    AuditPlanner,
    Budget,
    BudgetTracker,
    CampaignReport,
    ProbeSpec,
    ResponseCache,
)
from .context import load_context
from .data import generate_dispatch, generate_staffing
from .evidence import EvidenceLog
from .gate import DEFAULT_THRESHOLDS, evaluate_gate, evaluate_gate_status
from .gate_ci import (
    append_verdict_log,
    decide_exit,
    load_gate_config,
    render_verdict_markdown,
    run_gate,
)
from .judges import (
    Judge,
    JudgeScore,
    LLMJudge,
    RefusalJudge,
    StereotypeJudge,
    ToneJudge,
    aggregate_judge_findings,
    group_label_rates,
    label_rate_gaps,
    ordinal_means,
    unscored_rate,
)
from .calibration import (
    DEFAULT_KAPPA_THRESHOLD,
    CalibrationHarness,
    CalibrationReport,
    cohen_kappa,
)
from .metrics import AuditResult, audit_disparities
from .probes import (
    BUILTIN_RELATIONS,
    MetamorphicRelation,
    Probe,
    ProbeBatch,
    check_equal_output,
    check_symmetry,
    evaluate_metamorphic,
    generate_adversarial,
    generate_counterfactuals,
    generate_llm_assisted,
    generate_metamorphic,
)
from .report import save_report
from .reports import (
    AGENTIC_RMF_MAPPING,
    FLAG_THRESHOLD_DEFAULT,
    AuditReport,
    build_report,
    mappings_for_report,
    rmf_section as agentic_rmf_section,
    save_agentic_report,
    to_html as agentic_to_html,
    to_markdown as agentic_to_markdown,
)
from .rmf import RMF_MAPPING
from .targets import (
    HuggingFaceTarget,
    OllamaTarget,
    OpenAICompatTarget,
    RagTarget,
    TabularTarget,
    Target,
)

__all__ = [
    "audit_disparities",
    "AuditResult",
    "generate_dispatch",
    "generate_staffing",
    "save_report",
    "evaluate_gate",
    "evaluate_gate_status",
    "DEFAULT_THRESHOLDS",
    "RMF_MAPPING",
    "load_context",
    "load_gate_config",
    "run_gate",
    "decide_exit",
    "render_verdict_markdown",
    "append_verdict_log",
    "EvidenceLog",
    "Target",
    "HuggingFaceTarget",
    "OllamaTarget",
    "OpenAICompatTarget",
    "RagTarget",
    "TabularTarget",
    "Probe",
    "ProbeBatch",
    "MetamorphicRelation",
    "BUILTIN_RELATIONS",
    "check_equal_output",
    "check_symmetry",
    "evaluate_metamorphic",
    "generate_adversarial",
    "generate_counterfactuals",
    "generate_llm_assisted",
    "generate_metamorphic",
    "AuditCampaign",
    "AuditPlanner",
    "Budget",
    "BudgetTracker",
    "CampaignReport",
    "GENERATORS",
    "ProbeSpec",
    "ResponseCache",
    "Judge",
    "JudgeScore",
    "LLMJudge",
    "StereotypeJudge",
    "RefusalJudge",
    "ToneJudge",
    "aggregate_judge_findings",
    "group_label_rates",
    "label_rate_gaps",
    "ordinal_means",
    "unscored_rate",
    "CalibrationHarness",
    "CalibrationReport",
    "cohen_kappa",
    "DEFAULT_KAPPA_THRESHOLD",
    "__version__",
    "AuditReport",
    "build_report",
    "save_agentic_report",
    "agentic_to_markdown",
    "agentic_to_html",
    "agentic_rmf_section",
    "mappings_for_report",
    "AGENTIC_RMF_MAPPING",
    "FLAG_THRESHOLD_DEFAULT",
]
